[2023-06-08 19:05:05,341] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_combustivel.create_cluster manual__2023-06-08T19:05:01.170656+00:00 [queued]>
[2023-06-08 19:05:05,352] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_combustivel.create_cluster manual__2023-06-08T19:05:01.170656+00:00 [queued]>
[2023-06-08 19:05:05,352] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-08 19:05:05,353] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2023-06-08 19:05:05,354] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-06-08 19:05:05,402] {taskinstance.py:1264} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster> on 2023-06-08 19:05:01.170656+00:00
[2023-06-08 19:05:05,409] {standard_task_runner.py:52} INFO - Started process 5476 to run task
[2023-06-08 19:05:05,414] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_combustivel', 'create_cluster', 'manual__2023-06-08T19:05:01.170656+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/dag_combustivel.py', '--cfg-path', '/tmp/tmpnfpicee_', '--error-file', '/tmp/tmpths6210v']
[2023-06-08 19:05:05,417] {standard_task_runner.py:77} INFO - Job 73: Subtask create_cluster
[2023-06-08 19:05:05,496] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_combustivel.create_cluster manual__2023-06-08T19:05:01.170656+00:00 [running]> on host b35b0064e2f2
[2023-06-08 19:05:05,592] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_combustivel
AIRFLOW_CTX_TASK_ID=create_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T19:05:01.170656+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-08T19:05:01.170656+00:00
[2023-06-08 19:05:05,594] {dataproc.py:625} INFO - Creating cluster: gcp-pipeline-cluster-new
[2023-06-08 19:05:27,558] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 639, in execute
    cluster = self._create_cluster(hook)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 568, in _create_cluster
    cluster = operation.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.ServiceUnavailable: 503 The zone 'projects/gcp-datapipeline-389020/zones/us-central1-b' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.
[2023-06-08 19:05:27,575] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=dag_combustivel, task_id=create_cluster, execution_date=20230608T190501, start_date=20230608T190505, end_date=20230608T190527
[2023-06-08 19:05:27,594] {standard_task_runner.py:92} ERROR - Failed to execute job 73 for task create_cluster
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 639, in execute
    cluster = self._create_cluster(hook)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 568, in _create_cluster
    cluster = operation.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.ServiceUnavailable: 503 The zone 'projects/gcp-datapipeline-389020/zones/us-central1-b' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.
[2023-06-08 19:05:27,620] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-08 19:05:27,680] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
